export const errorMap = {
    "error.api.link.unsupported": {"zh-TW": "不支援的服務", "en-US": "Unsupported service", "ja-JP": "サポートされていないサービス", "ko-KR": "지원되지 않는 서비스", "tr-TR": "Desteklenmeyen hizmet"},
    "error.api.link.invalid": {"zh-TW": "無效的網址", "en-US": "Invalid URL", "ja-JP": "無効なURL", "ko-KR": "잘못된 URL", "tr-TR": "Geçersiz URL"},
    "error.api.invalid_body": {"zh-TW": "無效的網址", "en-US": "Invalid URL", "ja-JP": "無効なURL", "ko-KR": "잘못된 URL", "tr-TR": "Geçersiz URL"},
    "error.api.link.missing": {"zh-TW": "尚未輸入網址", "en-US": "URL not entered", "ja-JP": "URLが入力されていません", "ko-KR": "URL이 입력되지 않았습니다", "tr-TR": "URL girilmedi"},
    "error.api.content.post.age": {"zh-TW": "影像設有年齡限制", "en-US": "Content has age restriction", "ja-JP": "コンテンツには年齢制限があります", "ko-KR": "비디오에 연령 제한이 있습니다", "tr-TR": "Videonun yaş sınırlaması var"},
    "error.api.content.too_long": {"zh-TW": "影片過長(限制180分鐘)", "en-US": "Video is too long (limit 180 minutes)", "ja-JP": "動画が長すぎます（180分制限）", "ko-KR": "비디오가 너무 깁니다 (제한 180 분)", "tr-TR": "Video çok uz"},
    "error.api.content.video.unavailable": {"zh-TW": "無法取得影片", "en-US": "Unable to retrieve video", "ja-JP": "動画が利用できません", "ko-KR": "비디오를 사용할 수 없음", "tr-TR": "Video kullanılamıyor"},
    "error.api.content.post.private": {"zh-TW": "影片為私人影片", "en-US": "The content is private", "ja-JP": "この動画は非公開です", "ko-KR": "비디오가 비공개입니다", "tr-TR": "Video özel"},
    "error.api.fetch.empty": {"zh-TW": "無法取得影片", "en-US": "Unable to retrieve video", "ja-JP": "動画が取得できません", "ko-KR": "비디오를 검색할 수 없음", "tr-TR": "Video alınamıyor"},
    "error.api.fetch.critical": {"zh-TW": "無法取得影片", "en-US": "Unable to retrieve video", "ja-JP": "動画が取得できません", "ko-KR": "비디오를 검색할 수 없음", "tr-TR": "Video alınamıyor"},
    "error.api.fetch.fail": {"zh-TW": "無法取得影片", "en-US": "Unable to retrieve video", "ja-JP": "動画が取得できません", "ko-KR": "비디오를 검색할 수 없음", "tr-TR": "Video alınamıyor"},
    "error.api.content.video.live": {"zh-TW": "無法下載直播影片", "en-US": "Unable to download live video", "ja-JP": "ライブ動画をダウンロードできません", "ko-KR": "라이브 비디오를 다운로드할 수 없습니다", "tr-TR": "Canlı video indirilemiyor"},
    "failToConnectToServer": {"zh-TW": "無法連線至伺服器", "en-US": "Unable to connect to the server.", "ja-JP": "サーバーに接続できません。", "ko-KR": "서버에 연결할 수 없습니다.", "tr-TR": "Sunucuya bağlanılamadı."},
    "unknownError": {"zh-TW": "未知的錯誤", "en-US": "Unknown error", "ja-JP": "未知のエラー", "ko-KR": "알 수 없는 오류", "tr-TR": "Bilinmeyen hata"},
};